version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - echo No build steps needed for this simple example
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - '**/*'
  discard-paths: yes
